<?php

/**
 * This is the model base class for the table "log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Log".
 *
 * Columns in table "log" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $create_date
 * @property string $category
 * @property string $description
 *
 */
abstract class BaseLog extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'log';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Log|Logs', $n);
    }

    public static function representingColumn() {
        return 'category';
    }

    public function rules() {
        return array(
            array('create_date, category, description', 'required'),
            array('create_date', 'numerical', 'integerOnly' => true),
            array('category', 'length', 'max' => 32),
            array('description', 'length', 'max' => 255),
            array('id, create_date, category, description', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'create_date' => Yii::t('app', 'Create Date'),
            'category' => Yii::t('app', 'Category'),
            'description' => Yii::t('app', 'Description'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('create_date', $this->create_date);
        $criteria->compare('category', $this->category, true);
        $criteria->compare('description', $this->description, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 50,
            ),
            'sort' => array(
                'defaultOrder' => 'id DESC'
            )
        ));
    }

    protected function afterFind() {
        // convert to display format
        $this->create_date = Yii::app()->getDateFormatter()->format(Yii::app()->params->dateFormat['long_time'], $this->create_date);
        parent::afterFind();
    }

}
