<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '(Stateroom number will be assigned according to the best availability)' => '艙房號碼將按最佳庫存安排',
  '(include taxes, fees and port expenses)' => '(包括碼頭稅及港口費)',
  '29 – 8 days prior to sailing = 70% of total Cruise Fare' => '出發前8-29天，退回30%郵輪票價',
  '45 – 30 days prior to sailing = 50% of total Cruise Fare' => '出發前30-45天，退回50%郵輪票價',
  '7 – 0 days prior to sailing = No refund' => '出發前0-7天，不能退款',
  'Accept Terms & Conditions' => '同意條款及細則',
  'Adults' => '成人',
  'All itineraries are subject to change without prior notice.' => '所有航線行程如有任何更改，恕不另行通知',
  'All stateroom phots are for reference only, its decoration may varies from one to the other and subject to final allocated stateroom.' => '以上艙房圖片謹供參考，個别艙房類別裝飾及罷設或有分別，以最終被分配艙房作準。',
  'All taxes, fees and port expenses will be refunded if cancel sailing.' => '如取消預訂，將退回所有碼頭稅及港口費',
  'Balance Due' => '餘額',
  'Cancellation Charges' => '退款',
  'Card Information' => '信用卡資料',
  'Card number' => '信用卡號碼',
  'Card number cannot be blank.' => '信用卡號碼不可空白',
  'Card number format invalid.' => '信用卡號碼不正確',
  'Card type' => '信用卡類別',
  'Card type cannot be blank.' => '信用卡類別不可空白',
  'Children' => '小童',
  'Citizenship' => '國藉',
  'Clicking the Next button will lock the room for 20 minutes.' => '按下一步即會保存房間20分鐘',
  'Cruise' => '郵輪',
  'Cruise Fare' => '郵輪票價',
  'Cruise Fare per head for first and second guest' => '第一位及第二位旅客之郵輪票價 (每位)',
  'Cruise Fare per head for third and forth guest' => '第三位及第四位旅客之郵輪票價 (每位)',
  'Cruise fares exclude service charges and gratuities, taxes, fees and port expenses.' => '郵輪票價不包括船上收取之服務小費、港口費及碼頭稅',
  'Cruise fares include accommodation, complimentary meals, snacks and drinks in selected dining venues.' => '郵輪票價包括郵輪艙房住宿、指定餐廳內之三餐、小吃及飲料',
  'click here' => '按此',
  'Date of Birth' => '出生日期',
  'Departure Date' => '出發日期',
  'Email' => '電郵',
  'Expiration date' => '到期日',
  'Expiration month cannot be blank.' => '到期月份不可空白',
  'Expiration year cannot be blank.' => '到期年份不可空白',
  'First Name' => '名字',
  'First Name on card' => '信用卡上之名字',
  'First Name on card cannot be blank.' => '信用卡上之名字不可空白',
  'Full payment will be charged when you book this sailing (except for Quantum of the Seas Free Air Promotion).' => '除「海洋量子號」送機票推廣外，預訂航程將全數收取郵輪票價',
  'Gender' => '性別',
  'Given Name on card' => '姓氏',
  'Guest' => '旅客',
  'HKD' => '港幣',
  'I acknowledge that I have read and accept the Terms of the above Cruise / Cruisetour Ticket Contract.' => '本人已閱讀及接納郵輪船票/套票之條款及細則',
  'If the above options do not meet your choice, please contact our customer service officer at +852 3189 3200 or fill out the equiry form' => '如以上選項未能滿足您的要求，請致電+852 3189 3200 聯絡我們的客戶服務員或填妥諮詢表',
  'Information' => '資料',
  'Itinerary' => '行程',
  'Last Name' => '姓氏',
  'Last Name on card' => '信用卡上之姓氏',
  'Last Name on card cannot be blank.' => '信用卡上之姓氏不可空白',
  'Maximum up to people' => '房間上限人數',
  'Mobile number' => '手動電話',
  'Name' => '姓名',
  'No Guest younger than the age twenty-one (21) will be assigned to a stateroom unless accompanied in the same stateroom by an adult twenty-one (21) years old or older for any sailings originating in North America. No Guest younger than the age eighteen (18) will be assigned to a stateroom unless accompanied in the same stateroom by an adult eighteen (18) years old or older for any sailings originating in South America, Europe, Asia, Australia and New Zealand. The Company retains the right, on rare occasions, to raise the minimum age to sail unaccompanied on any sailing when local laws require or permit such a modification. A guest\'s age is established upon the first date of sailing.' => '預訂北美洲航線，21歲以下之旅客必須由一位21歲以上的旅客同行及入住同一艙房；預訂南美洲、歐洲、亞洲及澳紐航線，18歲以下之旅客必須由一位18歲以上的旅客同行及入住同一艙房。所有年齡限制有機會随當地法律而有所更改。旅客的年齡以出發的第一日計算。',
  'No. of Staterooms' => '艙房數量',
  'Note 1: the above offer should be able to applied to selective stateroom category OR to all categories' => '注意 1:以上優惠適用於指定艙房類別或所有類別',
  'Note 2: the above % discount offer only applied to cruise fare, guests have to pay respective NCCF, taxes, fees, prot expenses and gratuities ' => '注意 2: 以上%折扣優惠只適用於郵輪票價,旅客必須繳付有關之服務小費、港口費及碼頭稅',
  'Passport Number' => '護照號碼',
  'Payment' => '付款',
  'Payment Breakdown' => '付款內容',
  'Payment Terms' => '付款條款及細則',
  'Payment failed, please try again later or contact us.' => '付款不能完成，請稍後再試或聯絡我們',
  'Personal Information Collection Statement' => '個人資料收集條文',
  'Please fill in the required information.' => '請填妥有關的資料',
  'Input errors: Please try again' => '輸入錯誤: 請再試',
  'Port of Departure' => '出發港口 ',
  'Promotion Code' => '優惠代碼',
  'Promotion Offer' => '優惠',
  'Promotion code invalid'  => '輸入代碼錯誤',
  '1. Wrong code or'   => '1. 代碼問題',
  '2. Stateroom category not applicable. Please try again.' => '2. 輸入代碼不適用於艙房類別。請再試！',
  'Remarks' => '備註',
  'Required Information' => '必須填寫',
  'Required filed: Please read and accept the terms & conditions.' => '必須填寫：閱讀及接納條款及細則',
  'Review' => '檢閱',
  'Room' => '艙房',
  'Sailing Date' => '郵輪航線日期',
  'Ship' => '郵輪',
  'Single Supplement' => '單人附加費',
  'Sold out' => '售罄',
  'Stateroom ' => '艙房 ',
  'Stateroom Category' => '艙房類別',
  'TOTAL' => '總金額',
  'Taxes, Fees and Port Expenses' => '港口費及碼頭稅',
  'Thank you' => '多謝',
  'That promotion code do not be allowed in this itinerary!' => '優惠代碼不適用於此航線',
  'Title' => '稱謂',
  'Total' => '總金額',
  'Total No. of Guests' => '總旅客人數',
  'We shall keep your personal data confidential at all times. All personal data collected will be in compliance with the Personal Data(Privacy) Ordinance under the law of Hong Kong.' =>
  '我們將時刻謹慎保存你的個人資料，並按香港個人資料（私隱）條例處理。',
  'YOUR CRUISE' => '您的郵輪',
  'Your Booking Reference Number is <span>{CODE}</span><br />
            Details of cruise document will be sent to you within the next two working days. <br />
            Meanwhile, you can plan your onboard agenda with various add-on package options. <br />
           Please visit our website <a href="mailto:sales@royalcaribbean.com.hk">www.royalcaribbean.com.hk</a> or should you have further questions, <br />
           please email us at <a href="mailto:sales@royalcaribbean.com.hk">sales@royalcaribbean.com.hk</a> <br />' =>
  '你的預訂編號為<span>{CODE}</span><br />
  我個將於兩個工作天後寄出正式郵輪文件到您的電郵信箱。<br />
  歡迎瀏覽<a href="mailto:sales@royalcaribbean.com.hk">www.royalcaribbean.com.hk</a>為您的旅程計劃更多額外套餐。<br />
  如有任何查詢，歡迎電郵致<a href="mailto:sales@royalcaribbean.com.hk">sales@royalcaribbean.com.hk</a> <br />',
  'test' => '',
  );
