<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '(include NCCF, taxes, fees and port expenses)' => '',
  'Accept Terms & Conditions' => '',
  'Adults' => '',
  'All itineraries are subject to change without prior notice.' => '',
  'Balance Due' => '',
  'Card Information' => '',
  'Card number' => '',
  'Card number cannot be blank.' => '',
  'Card number format invalid.' => '',
  'Card type' => '',
  'Card type cannot be blank.' => '',
  'Children' => '',
  'Clicking the Next button will lock the room for a duration of 20 minutes.' => '',
  'Cruise' => '',
  'Cruise Fare' => '',
  'Cruise Fare Breakdown' => '',
  'Cruise Fare per head for first and second guests' => '',
  'Cruise Fare per head for third and forth guests' => '',
  'Cruise fares exclude service charges and gratuities, taxes, fees and port expenses.' => '',
  'Cruise fares include NCCF , accommodation, complimentary meals, snacks and drinks in selected dining venues.' => '',
  'Departure Date' => '',
  'Expiration date' => '',
  'Expiration month cannot be blank.' => '',
  'Expiration year cannot be blank.' => '',
  'Family Name on card' => '',
  'Family Name on card cannot be blank.' => '',
  'Fare' => '',
  'Given Name on card' => '',
  'Given Name on card cannot be blank.' => '',
  'Guest' => '',
  'If the above options do not meet your choice, please contact our customer service officer at +852 3189 3200 or fill out the equiry form' => '',
  'Information' => '',
  'Itinerary' => '',
  'No Guest younger than the age twenty-one (21) will be assigned to a stateroom unless accompanied in the same stateroom by an adult twenty-one (21) years old or older. A guest\'s age is established upon the first date of sailing.' => '',
  'No. of Staterooms' => '',
  'Note 1: the above offer should be able to applied to selective stateroom category OR to all categories' => '',
  'Note 2: the above % discount offer only applied to cruise fare, guests have to pay respective NCCF, taxes, fees, prot expenses and gratuities ' => '',
  'Payment' => '',
  'Payment failed, please try again later or contact us.' => '',
  'Please agree to the Terms & Conditions to continue.' => '',
  'Please fill in the required information.' => '',
  'Please fix the following input errors' => '',
  'Port of Departure' => '',
  'Promotion Code ' => '',
  'Promotion Offer' => '',
  'Promotional Content' => '',
  'Remarks' => '',
  'Required Information' => '',
  'Review' => '',
  'Sailing Dates' => '',
  'Ship' => '',
  'Single Supplement' => '',
  'Sold out' => '',
  'Stateroom Category' => '',
  'TOTAL' => '',
  'Taxes, Fees and Port Expenses' => '',
  'Thank you' => '',
  'Thank you for your Online Payment.<br />
            Please make a note of your Booking Reference Number <span>{CODE}</span><br />
            Your reservation details will be sent to your email address within the next two working days.<br />
            Should you have any questions or concerns about this transaction,<br />
            please contact the Booking Hotline: +852 3189 3200 or <br />
            email: <a href="mailto:sales@royalcaribbean.com.hk">sales@royalcaribbean.com.hk</a><br />' => '',
  'Those who book suite could enjoy complimentary flower bouquet, champagne and local round-trip transfer\'s' => '',
  'Total' => '',
  'Total No. of Guests' => '',
  'YOUR CRUISE' => '',
  'test' => '',
);
