<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'All items add. Old items remain unchanged' => '',
  'CSV column' => '',
  'CSV field' => '',
  'Download file is not a .csv' => '',
  'Error' => '',
  'Errors in rows' => '',
  'Fields Delimiter' => '',
  'Fields Delimiter can not be empty' => '',
  'File' => '',
  'For this mode' => '',
  'If you use &laquo;Insert new&raquo; or &laquo;Insert new and replace old&raquo; mode, you need to select a key field from table and from csv. Using this fields script will realize is this row new or old' => '',
  'Import' => '',
  'Import was carried out' => '',
  'Insert all' => '',
  'Insert new' => '',
  'Insert new and replace old' => '',
  'Items per one request' => '',
  'Keys for compare' => '',
  'Mode' => '',
  'New items add. Old items remain unchanged' => '',
  'New items add. Old items replace' => '',
  'Next' => '',
  'No' => '',
  'No one column is selected' => '',
  'Notes' => '',
  'Select CSV File' => '',
  'Start over' => '',
  'Table' => '',
  'Table column' => '',
  'Table field' => '',
  'Text Delimiter' => '',
  'Unable to upload file' => '',
  'and' => '',
  'must be a number' => '',
  'must be selected' => '',
  'must not be empty' => '',
);
